# Generated by Django 4.0.4 on 2023-04-03 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_patient_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
