# Generated by Django 4.0.4 on 2023-04-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_patient_date_alter_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.TextField(),
        ),
    ]
