# Generated by Django 4.0.4 on 2023-04-03 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_alter_patient_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type',
            field=models.TextField(max_length=50),
        ),
    ]
