# Generated by Django 4.0.4 on 2023-04-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_alter_patient_date_alter_patient_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
