# Generated by Django 4.0.4 on 2023-04-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_alter_patient_date_alter_patient_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
