# Generated by Django 4.0.4 on 2023-04-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_alter_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='type',
            field=models.BooleanField(),
        ),
    ]
