# Generated by Django 4.0.4 on 2023-04-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_alter_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
