# Generated by Django 4.0.4 on 2023-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0010_alter_patient_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
